# Ideer til problemstillinger

1. Er der en sammenhæng mellem COO (produktionsland) og pris og/eller, hvorvidt brugeranmeldelser er positive?
2. I hvilke lande eller regioner finder man højt-ratede "billige" vine?
3. Hvordan ser ratings på vine ud set fra et lande-perspektiv? Kan det udledes, hvilke typer vin, hvilke druer eller hvilke lande/regioner et bestemt land rater højest? (baseret på brugeranmeldelser). Ideen er at kunne facilitere en forhandler/importør af vin med et værktøj, der kan fortælle, hvilke slags vin, eksempelvis danskerne rater højt, med henblik på afsætningsoptimering.
4. Hvor godt kan prisen på en vin estimeres på baggrund af dets land?
5. Kan ratings predikteres ud fra indhold af sukker, syre etc. ?

In [1]:
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import time
import tqdm

start_time = time.time()


#start webdriver and load the page:
url = 'https://www.vivino.com/scarecrow-cabernet-sauvignon/w/1611255?year=2014'
driver = webdriver.Chrome(ChromeDriverManager().install())
driver.get(url)
time.sleep(5)

lenOfPage = driver.execute_script("window.scrollTo(0, document.body.scrollHeight);var lenOfPage=document.body.scrollHeight;return lenOfPage;")
match=False
while(match==False):
    lastCount = lenOfPage
    time.sleep(8)
    lenOfPage = driver.execute_script("window.scrollTo(0, document.body.scrollHeight);var lenOfPage=document.body.scrollHeight;return lenOfPage;")
    if lastCount==lenOfPage:
        match=True
        
time.sleep(5)

soup = BeautifulSoup(driver.page_source, 'lxml')
print("--- %s seconds ---" % round((time.time() - start_time),2))

[WDM] - Current google-chrome version is 84.0.4147
[WDM] - Get LATEST driver version for 84.0.4147
[WDM] - Get LATEST driver version for 84.0.4147

[WDM] - Trying to download new driver from http://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_win32.zip
[WDM] - Driver has been saved in cache [C:\Users\lasse\.wdm\drivers\chromedriver\win32\84.0.4147.30]

--- 35.1 seconds ---

In [22]:
test = soup.find_all('a', class_='anchor__anchor--2QZvA wineSummary__link--zVpWl')
names = []
for x in test:
    names.append(x.text)
print(type(names))
print(names)
import pandas as pd
headers = ['Wine name']
df = pd.DataFrame(names, columns=headers)
df

<class 'list'>
['Scarecrow', '100% Cabernet Sauvignon', 'Rutherford', 'Napa Valley Cabernet Sauvignon', 'Oksekød', 'Lammekød', 'Vildt (rådyr, hjort)', 'Fjerkræ']

                        Wine name
0                       Scarecrow
1         100% Cabernet Sauvignon
2                      Rutherford
3  Napa Valley Cabernet Sauvignon
4                         Oksekød
5                        Lammekød
6            Vildt (rådyr, hjort)
7                         Fjerkræ

In [30]:
test = soup.find_all('a', class_='anchor__anchor--2QZvA wineSummary__link--zVpWl')
grape = test[1].text
wine_name = test[0].text

print(wine_name)
print(grape)

names = []
for x in test:
    names.append(x.text)
print(type(names))
print(names)
import pandas as pd
headers = ['Wine name']
df = pd.DataFrame(names, columns=headers)
df

Scarecrow
100% Cabernet Sauvignon
<class 'list'>
['Scarecrow', '100% Cabernet Sauvignon', 'Rutherford', 'Napa Valley Cabernet Sauvignon', 'Oksekød', 'Lammekød', 'Vildt (rådyr, hjort)', 'Fjerkræ']

                        Wine name
0                       Scarecrow
1         100% Cabernet Sauvignon
2                      Rutherford
3  Napa Valley Cabernet Sauvignon
4                         Oksekød
5                        Lammekød
6            Vildt (rådyr, hjort)
7                         Fjerkræ

In [247]:
wine_name = soup.find_all('span', {'class':'vintageTitle__wine--U7t9G'})
region_name = soup.body.find_all('a', class_='anchor__anchor--2QZvA vintageLocation__anchor--T7J3k')

name_region = []
names = []
for x in wine_name:
    names.append(x.text)

import pandas as pd
headers = ['Wine name']
df = pd.DataFrame(names, columns=headers)
df

                                              Wine name
0                Raro Cabernet Sauvignon Selezione 2007
1                        Barolo Riserva Monfortino 1985
2     La Fabriseria Amarone della Valpolicella Class...
3                                 Barolo Lazzarito 2000
4             Basaltico Amarone della Valpolicella 2004
...                                                 ...
5845                         Barolo Vigneto Rocche 2007
5846           Amarone della Valpolicella Classico 2015
5847                     Gramolere  Barolo Riserva 1998
5848                            Bricco Soria Rosso 2008
5849           Amarone della Valpolicella Classico 2001

[5850 rows x 1 columns]

In [241]:
df2 = df.drop_duplicates()
df2

                                              Wine name
0                Raro Cabernet Sauvignon Selezione 2007
1                        Barolo Riserva Monfortino 1985
2     La Fabriseria Amarone della Valpolicella Class...
3                                 Barolo Lazzarito 2000
4             Basaltico Amarone della Valpolicella 2004
...                                                 ...
2017                           Nuao 273 Montalcino 2015
2018           Vigneto Bellavista Chianti Classico 2001
2021                         Barolo Vigneto Rocche 2007
2023                     Gramolere  Barolo Riserva 1998
2024                            Bricco Soria Rosso 2008

[1786 rows x 1 columns]